task :default do
  sh "pdflatex aaai_kr_workshop.tex"
  sh "bibtex aaai_kr_workshop"
  sh "pdflatex aaai_kr_workshop.tex"
  sh "pdflatex aaai_kr_workshop.tex"
end
task :clean do
  sh "rm -rf *.aux *.blg *.log"
end
